openapi: '3.0.2'
info:
  title: KAOS
  description: For additional general information on how to use this API please refer to the [additional documentation](./docs.html).
  version: '0.0.1'
x-tagGroups:
  - name: Network Management
    tags:
      - Networks
      - Network Authorizations
      - Network Venues
  - name: User Management
    tags:
      - Users
  - name: Portfolio Management
    tags:
      - Portfolios
      - Child Portfolios
      - Members
  - name: Unit Management
    tags:
      - Locations
      - Roles
      - Teams
      - Units
paths:
  /locations:
    $ref: '/home/james/Code/kaos/openapi/definition/locations.yml#/paths/locations'
  /locations/{locationId}:
    $ref: '/home/james/Code/kaos/openapi/definition/locations.yml#/paths/location'
  /locations/{locationId}/units:
    $ref: '/home/james/Code/kaos/openapi/definition/locations.yml#/paths/locationUnits'
  /networks:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/networks'
  /networks/{networkId}:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/network'
  /networks/{networkId}/authorizations:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/authorizationAttributes'
  /networks/{networkId}/authorizations/{authorizationId}:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/authorizationAttribute'
  /networks/{networkId}/venues:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/venueTypes'
  /networks/{networkId}/venues/{venueId}:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/venueType'
  /portfolios:
    $ref: './portfolio.yml#/paths/portfolios'
  /portfolios/{portfolioId}:
    $ref: './portfolio.yml#/paths/portfolio'
  /portfolios/{portfolioId}/child-portfolios/{childPortfolioId}:
    $ref: './portfolio.yml#/paths/childPortfolio'
  /portfolios/{portfolioId}/members:
    $ref: './portfolio.yml#/paths/portfolioMembers'
  /portfolios/{portfolioId}/members/{userId}:
    $ref: './portfolio.yml#/paths/portfolioMember'
  /units:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/units'
  /units/{unitId}:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unit'
  # /units/{unitId}/members:
  #   $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unitMembers'
  # /units/{unitId}/members/{userId}:
  #   $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unitMember'
  /units/{unitId}/authorizatonRoles/{userId}:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unitAuthorizationRoles'
  /units/{unitId}/teams:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unitTeams'
  /units/{unitId}/teams/{teamId}:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unitTeam'
  /users:
    $ref: '/home/james/Code/kaos/openapi/definition/users.yml#/paths/users'
  /users/{userId}:
    $ref: '/home/james/Code/kaos/openapi/definition/users.yml#/paths/user'