openapi: '3.0.2'
info:
  title: KAOS
  description: For additional general information on how to use this API please refer to the [additional documentation](./docs.html).
  version: '0.0.1'
x-tagGroups:
  - name: Communications
    tags:
      - Channels
      - Channel Members
      - Posts
  - name: Locations
    tags:
      - Locations
  - name: Network Management
    tags:
      - Networks
      - Network Authorizations
      - Network Venues
  - name: User Management
    tags:
      - Users
      - User Personal
      - User Units
  - name: Unit Management
    tags:
      - Units
      - Unit Members
      - Sub Units
paths:
  /channels:
    $ref: './communications.yml#/paths/channels'
  /channels/{channelId}:
    $ref: './communications.yml#/paths/channel'
  /channels/{channelId}/posts:
    $ref: './communications.yml#/paths/channelPosts'
  /channels/{channelId}/posts/{postId}:
    $ref: './communications.yml#/paths/channelPost'
  /channels/{channelId}/members/{userId}:
    $ref: './communications.yml#/paths/channelMembers'
  /locations:
    $ref: './locations.yml#/paths/locations'
  /locations/{locationId}:
    $ref: './locations.yml#/paths/location'
  /networks:
    $ref: './networks.yml#/paths/networks'
  /networks/{networkId}:
    $ref: './networks.yml#/paths/network'
  /networks/{networkId}/venues:
    $ref: './networks.yml#/paths/venueTypes'
  /networks/{networkId}/venues/{venueId}:
    $ref: './networks.yml#/paths/venueType'
  /units:
    $ref: './units.yml#/paths/units'
  /units/{unitId}:
    $ref: './units.yml#/paths/unit'
  /units/{unitId}/members:
    $ref: './units.yml#/paths/unitMembers'
  /units/{unitId}/members/{userId}:
    $ref: './units.yml#/paths/unitMember'
  /units/{unitId}/subUnits/{subUnitId}:
    $ref: './units.yml#/paths/subUnits'
  /users:
    $ref: './users.yml#/paths/users'
  /users/{userId}:
    $ref: './users.yml#/paths/user'
  /users/{userId}/personal:
    $ref: './users.yml#/paths/userPersonal'
components:
  schemas:
    ChannelPost:
      $ref: './communications.yml#/components/schemas/Post'
    ChannelMarketplacePost:
      $ref: './communications.yml#/components/schemas/MarketplacePost'
    UnitTypeRetailer:
      $ref: './units.yml#/components/schemas/UnitTypeRetailer'
    UnitTypeTeam:
      $ref: './units.yml#/components/schemas/UnitTypeTeam'
    UnitTypeVenue:
      $ref: './units.yml#/components/schemas/UnitTypeVenue'
