openapi: '3.0.2'
info:
  title: KAOS
  version: '0.0.1'
x-tagGroups:
  - name: Network Management
    tags:
      - Networks
      - Metadata
  - name: User Management
    tags:
      - Users
  - name: Unit Management
    tags:
      - Locations
      - Members
      - Roles
      - Teams
      - Units
paths:
  /locations:
    $ref: '/home/james/Code/kaos/openapi/definition/locations.yml#/paths/locations'
  /locations/{locationId}:
    $ref: '/home/james/Code/kaos/openapi/definition/locations.yml#/paths/location'
  /locations/{locationId}/units:
    $ref: '/home/james/Code/kaos/openapi/definition/locations.yml#/paths/locationUnits'
  /networks:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/networks'
  /networks/{networkId}:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/network'
  /networks/{networkId}/meta:
    $ref: '/home/james/Code/kaos/openapi/definition/networks.yml#/paths/networkMeta'
  /units:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/units'
  /units/{unitId}:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unit'
  /units/{unitId}/members:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unitMembers'
  /units/{unitId}/members/{userId}:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unitMember'
  /units/{unitId}/authorizatonRoles/{userId}:
    $ref: '/home/james/Code/kaos/openapi/definition/units.yml#/paths/unitAuthorizationRoles'
  /units/{unitId}/teams:
    $ref: '/home/james/Code/kaos/openapi/definition/units_teams.yml#/paths/teams'
  /users:
    $ref: '/home/james/Code/kaos/openapi/definition/users.yml#/paths/users'
  /users/{userId}:
    $ref: '/home/james/Code/kaos/openapi/definition/users.yml#/paths/user'